
# -*- coding: utf-8 -*-
import sqlite3
#Подключение к базе
conn = sqlite3.connect('my.sqlite')
#Создание курсора
c = conn.cursor()
###################################################################################################
c.execute('''CREATE TABLE  IF NOT EXISTS test (test_id int, name  text)''')
c.execute ("DELETE FROM test")
c.execute("INSERT INTO test (test_id,name) VALUES (1,'Рок')")
c.execute("INSERT INTO test (test_id,name) VALUES (2,'Рэп')")
c.execute("INSERT INTO test (test_id,name) VALUES (3,'Классика')")
c.execute("INSERT INTO test (test_id,name) VALUES (4,'Поп')")
conn.commit()
#################################
##############################################################################################
c.execute('''CREATE TABLE IF NOT EXISTS question (que_id int, quest  text,test_id int)''')
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (1,'Слово “love” встречается 613 раз в песнях именно этой группы:',1)")
c.execute ("DELETE FROM question")
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (2,'Какая из этих групп НЕ трио?',1)")
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (3,'Какая группа попала в книгу рекордов Гиннеса, отыграв концерты на всех семи континентах планеты (в том числе и в Антарктиде)',1)")
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (4,'Песни какой группы повлияли на творчество А.Васильева («Сплин»)',1)")
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (5,'Альбом какой группы побил все рекорды, продержавшись на вершинах чартов 741 неделю?',1)")
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (6,'Какой музыкант был хозяином шотландского терьера по кличке Билл?',1)")
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (7,'Кто из музыкантов прожил больше остальных?',1)")
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (8,'Какая из этих групп назвалась в честь футбольной команды?',1)")
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (9,'Кто из музыкантов прожил больше остальных?',1)")
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (10,'Какая из этих групп назвалась в честь футбольной команды?',1)")
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (11,'Именно в этом году среди рабочего класса Нью-Йорка зародилось понятие хип-хоп',2)") 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (12,'Самый богатый рэпер на планете',2)") 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (13,'Кто одним из первых стал исполнителем жанра Hustle',2)") 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (14,'Как называлась первая рэп-команда СССР',2)") 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (15,'Назовите самого популярного рэпера планеты',2)") 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (16,'Именно столько миллионов долларов зарабатывает рэпер Тимати за год:',2)") 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (17,'Какой музыкальный лейбл России популярнее остальных?',2)") 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (18,'В ремейке какого фильма снялся рэпер Noize MC?',2)") 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (19,'В каком коллективе выступал Батишта до начала сольной карьеры?',2)") 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (20,'Назовите известную песню рэпера Lizer',2)") 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (21,'Музыка какого композитора повлияла на Адольфа Гитлера?',3)") 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (22,'Император Николай I не любил музыку и в качестве наказания для офицеров предлагал им выбрать между гауптвахтой и…',3)") 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (23,'И.С.Бах не единственный композитор из своей семьи. Сколько было Бахов-музыкантов в истории музыки?',3)") 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (24,'В каком возрасте Моцарт стал сочинять музыку',3)") 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (25,'Кто из этих композиторов был националистом?',3)") 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (26,'Назовите диапазон известного российского певца Сергея Пенкина (количество октав)',3)") 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (27,'О каком известном композиторе и музыканте была написана маленькая трагедия А.С. Пушкина',3)") 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (28,'Самый большой оркестр в мире',3)") 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (29,'Сколько ступеней должен содержать полноценный аккорд',3)") 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (30,'Сколько струн в контрабасе?',3)") 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (31,'Кто из этих певиц начал свой музыкальный путь в церковном хоре?',4)")
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (32,'Песни какой певицы использовала британская армия для отпугивания сомалийских пиратов?',4)")
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (33,'Какой исполнитель завоевал победу на Евровидении-2009 в Москве?',4)")
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (34,'Какая извстеная поп-исполнительница появляется в клипе Katty Peryy: I kissed a girl,',4)")
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (35,'Чей дебютный альбом …Baby One More Time стал 15-кратным платиновым и на сегодняшний день является самым успешным альбомом данного исполнителя',4)")
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (36,'На основе песен какой группы был поставлен мюзикл Mamma Mia!',4)")
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (37,'Где родился Justin Bieber',4)") 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (38,'Какое место заняла Майли Сайрус в списке величайших поп-исполнительниц по версии VH1',4)") 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (39,'Как зовут сына певца Хулио Иглесиаса?',4)") 
c.execute("INSERT INTO question (que_id,quest,test_id) VALUES (40,'С кем из данных исполнительниц  встречался Джастин Бибер',4)") 
conn.commit()
#######################################################################################3


c.execute('''CREATE TABLE IF NOT EXISTS answer(answer_id int, ans text, que_id int)''' )
c.execute( "DELETE FROM answer")
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (1,'1)The Beatles\n 2)Rolling Stones\n 3)Chris Isaak\n',1)")
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (2,'1)Muse\n 2)Arctic Monkeys\n 3)Green Day\n',2)")
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (3,'1)Metallica\n 2)AC/DC\n 3)Led Zeppelin\n',3)")
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (4,'1)Nirvana\n 2)Sex Pistols\n 3)Radiohead\n',4)")
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (5,'1)Red Hot Chili Peppers\n 2)Pink Floyd\n 3)The Beatles\n',5)")
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (6,'1)Виктор Цой\n 2)Константин Кинчев\n 3)Борис Гребенщиков\n',6)")
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (7,'1)Курт Кобейн\n 2)Брайан Джонс\n 3)Виктор Цой\n',7)")
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (8,'1)Kaiser Chiefs\n 2)Rammstein\n 3)Depeche Mode\n',8)")
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (9,'1)Чтобы он научил их лучше владеть гитарой\n 2)Чтобы спасти группу от развала\n 3)Чтобы он покупал им алкоголь\n',9)")
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (10,'1)Бесполезные идиомы\n 2)Берег истины\n 3)Бриллиантовые иллюзии\n',10)")
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (11,'1)1955\n 2)1967\n 3)1974',11)") 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (12,'1)Тимати\n 2)Dr.Dre\n 3)Wooteng',12)") 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (13,'1)2pac\n 2)Flo Rida\n 3)Dr.Dre',13)") 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (14,'1)Берег слоновой кости\n 2)USSR\n 3)DMJ',14)")
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (15,'1)Flo Rida\n 2)Eminem\n 3)Lil pump',15)") 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (16,'1)201\n 2)301\n 3)251',16)") 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (17,'1)Gazgolder\n 2)Black Star\n 3)MALFA ',17)") 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (18,'1)Розыгрыш\n 2)Экипаж\n 3)Джентельмены удачи ',18)") 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (19,'1)Бумбокс\n 2)БАНД’ЭРОС\n 3)Йорш ',19)") 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (20,'1)Black swan\n 2)Blach wall\n 3)Black mirror',20)") 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (21,'1)Вагнер\n 2)Бетховен\n 3)Бах\n',21)") 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (22,'1)Прослушиванием опер Глинки\n 2)Пением придворных оперных певиц\n 3)Прослушиванием криков павлинов\n',22)") 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (23,'1)5\n 2)25\n 3)50\n',23)") 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (24,'1)5\n 2)10\n 3)13\n',24)") 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (25,'1)Вагнер\n 2)Дж.Верди\n 3)Бетховен\n',25)") 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (26,'1)3\n 2)4\n 3)5\n',26)") 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (27,'1)Бетховен\n 2)Чайковский\n 3)Моцарт\n',27)") 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (28,'1)2115 музыкантов\n 2)6017 музыкантов\n 3)4629 музыкантов\n',28)") 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (29,'1)3\n 2)2\n 3)5\n',29)") 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (30,'1)5\n 2)4\n 3)Ни один вариант не подходит\n',30)") 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (31,'1)Beyoncé\n 2)Katy Perry\n 3)Selena Gomez\n',31)")
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (32,'1)Britney Spears\n 2)Элла Фицджеральд\n 3)Лариса Долина\n',32)")
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (33,'1)Дима Билан\n 2)Алексей Воробьев\n 3)Александр Рыбак\n',33)")
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (34,'1)Kesha\n 2)Britney Spears\n 3)Miley Cyrus\n',34)")
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (35,'1)Selena Gomez\n 2)Taylor Swift\n 3)Britney Spears\n',35)")
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (36,'1)ABBA\n, 2)Maroon5\n 3)Coldplay\n',36)")
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (37,'1)США\n 2)Канада\n 3)Англия\n',37)") 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (38,'1)23\n 2)84\n 3)99\n',38)") 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (39,'1)Энрике\n 2)Альберто\n 3)Густаво\n',39)") 
c.execute("INSERT INTO answer (answer_id,ans,que_id) VALUES (40,'1)Селена Гомез\n 2)Майли Сайрус\n 3)Аврил Лавин\n',40)") 
conn.commit() 
##################################################################################################################3


c.execute('''CREATE TABLE IF NOT EXISTS correct(cor_id int , cor_a text, answer_id int)''')
c.execute("DELETE FROM correct")
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(1,'The Beatles',1)")
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(2,'Arctic Monkeys',2)")
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(3,'Metallica',3)")
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(4,'Radiohead',4)")
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(5,'Pink Floyd',5)")
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(6,'Виктор Цой',6)")
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(7,'Виктор Цой',7)")
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(8,'Kaiser Chiefs',8)")
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(9,'Чтобы он покупал им алкоголь',9)")
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(10,'Берег истины',10)")
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(11,'1974',11)") 
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(12,'Dr.Dre',12)") 
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(13,'2pac',13)") 
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(14,'DMJ',14)") 
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(15,'Eminem',15)") 
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(16,'201',16)") 
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(17,'Black Star',17)") 
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(18,'Розыгрыш',18)") 
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(19,'БАНД’ЭРОС',19)") 
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(20,'Black mirror',20)") 
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(21,'Вагнер',21)") 
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(22,'Прослушиванием опер Глинки',22)") 
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(23,'50',23)") 
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(24,'5',24)") 
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(25,'Дж.Верди',25)") 
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(26,'4',26)") 
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(27,'Моцарт',27)") 
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(28,'6017 музыкантов',28)") 
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(29,'3',29)") 
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(30,'4',30)") 
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(31,'Katty Perry',31)")
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(32,'Britney Spears',32)")
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(33,'Александр Рыбак',33)")
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(34,'Kesha',34)")
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(35,'Britney Spears',35)")
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(36,'ABBA',36)")
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(37,'Канада',37)") 
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(38,'84',38)") 
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(39,'Энрике',39)") 
c.execute("INSERT INTO correct (cor_id,cor_a,answer_id) VALUES(40,'Селена Гомез',40)") 
conn.commit()






c.execute('''CREATE TABLE IF NOT EXISTS u_answer(u_answer_id int, u_ans_text text, answer_id int)''')
c.execute('''CREATE TABLE IF NOT EXISTS  result(result_id int , user_res int, u_answer_id int, cor_id int)''')
c.execute('''CREATE TABLE IF NOT EXISTS  testsww1 (id integer, question  text , ans text, correct text)''')
